[package]
name = "day-03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part_1"
path = "src/bin/part_1.rs"

[[bin]]
name = "part_2"
path = "src/bin/part_2.rs"

[dependencies]
common = { path = "../common" }
regex = "1.10.2"
